import styles from "./index.module.css";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignIn } from "@clerk/nextjs";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>CZ T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Create <span className={styles.pinkSpan}>T3</span> App CZ
        </h1>
        <button className="btn btn-primary">button</button>
        <button className="btn btn-secondary">button</button>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
}
